certificateAuthorities:
  orderer-ca.orderer:
    caName: ca
    registrar:
      enrollId: enroll
      enrollSecret: enrollpw
    tlsCACerts:
      pem:
      - |
        -----BEGIN CERTIFICATE-----
        MIICajCCAhCgAwIBAgIRAP4dJRgwjfsHSqSzlD8ZNLcwCgYIKoZIzj0EAwIwUjET
        MBEGA1UEBhMKQ2FsaWZvcm5pYTEJMAcGA1UEBxMAMQkwBwYDVQQJEwAxFDASBgNV
        BAoTC0h5cGVybGVkZ2VyMQ8wDQYDVQQLEwZGYWJyaWMwHhcNMjMxMTIxMTYxMDQ4
        WhcNMzMxMTIyMTYxMDQ4WjBSMRMwEQYDVQQGEwpDYWxpZm9ybmlhMQkwBwYDVQQH
        EwAxCTAHBgNVBAkTADEUMBIGA1UEChMLSHlwZXJsZWRnZXIxDzANBgNVBAsTBkZh
        YnJpYzBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABDs2ydbFvK+Ar0BtImXHSsia
        r3w6suRvDtCdF/D4sqqqKUD0efN2IwqeIcNBWczooI5UYv2Yi77AvcoxgNtFlgWj
        gcYwgcMwDgYDVR0PAQH/BAQDAgGmMB0GA1UdJQQWMBQGCCsGAQUFBwMCBggrBgEF
        BQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1UdDgQiBCD75SBSDe98rl4mU0QU0ct/
        2UpDARUF8zc0uMhxBBgmAjBWBgNVHREETzBNgglsb2NhbGhvc3SCCm9yZGVyZXIt
        Y2GCEm9yZGVyZXItY2Eub3JkZXJlcoIab3JkZXJlci1jYS5obGYuY2hpa2l0c2Eu
        aW+HBH8AAAEwCgYIKoZIzj0EAwIDSAAwRQIgRY4C4a8gR5yK4rLUmqEhPbEg4X46
        ynj95Jtik/L35/oCIQCCzMqqeF9cV3TRaeDm4vcyWL8I0sQq3soDDvDVPBnNTw==
        -----END CERTIFICATE-----
    url: https://orderer-ca.hlf.chikitsa.io:443
  org1-ca.org1:
    caName: ca
    registrar:
      enrollId: enroll
      enrollSecret: enrollpw
    tlsCACerts:
      pem:
      - |
        -----BEGIN CERTIFICATE-----
        MIICXjCCAgSgAwIBAgIRAOs6QfNU/0hiwofiZlgB344wCgYIKoZIzj0EAwIwUjET
        MBEGA1UEBhMKQ2FsaWZvcm5pYTEJMAcGA1UEBxMAMQkwBwYDVQQJEwAxFDASBgNV
        BAoTC0h5cGVybGVkZ2VyMQ8wDQYDVQQLEwZGYWJyaWMwHhcNMjMxMTIxMTYxMDA4
        WhcNMzMxMTIyMTYxMDA4WjBSMRMwEQYDVQQGEwpDYWxpZm9ybmlhMQkwBwYDVQQH
        EwAxCTAHBgNVBAkTADEUMBIGA1UEChMLSHlwZXJsZWRnZXIxDzANBgNVBAsTBkZh
        YnJpYzBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABCBZSFi4YY61/modsxeDVQCZ
        oEImNsuzuEsH3BI7kf2qyGfXX5QPGYm0PfMJ8RPAY+ZZvI87IZ0tJZAHALSaKqWj
        gbowgbcwDgYDVR0PAQH/BAQDAgGmMB0GA1UdJQQWMBQGCCsGAQUFBwMCBggrBgEF
        BQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1UdDgQiBCCcRsiVYTeo63e6VJ3UMhIf
        87iNokTMAFhCyqkuzieBtDBKBgNVHREEQzBBgglsb2NhbGhvc3SCB29yZzEtY2GC
        DG9yZzEtY2Eub3JnMYIXb3JnMS1jYS5obGYuY2hpa2l0c2EuaW+HBH8AAAEwCgYI
        KoZIzj0EAwIDSAAwRQIhAOJOXVJNXwhCAkYeym3gEB7XvfzI5duxLv1HmwCNsmJ/
        AiApKxgWHitHXSwJOvOr3mCnPYsvyXcZcaFfMPjZDZZd1g==
        -----END CERTIFICATE-----
    url: https://org1-ca.hlf.chikitsa.io:443
  org2-ca.org2:
    caName: ca
    registrar:
      enrollId: enroll
      enrollSecret: enrollpw
    tlsCACerts:
      pem:
      - |
        -----BEGIN CERTIFICATE-----
        MIICXjCCAgOgAwIBAgIQen71hlTnMW93qdYiWrl6ajAKBggqhkjOPQQDAjBSMRMw
        EQYDVQQGEwpDYWxpZm9ybmlhMQkwBwYDVQQHEwAxCTAHBgNVBAkTADEUMBIGA1UE
        ChMLSHlwZXJsZWRnZXIxDzANBgNVBAsTBkZhYnJpYzAeFw0yMzExMjExNjEwMjha
        Fw0zMzExMjIxNjEwMjhaMFIxEzARBgNVBAYTCkNhbGlmb3JuaWExCTAHBgNVBAcT
        ADEJMAcGA1UECRMAMRQwEgYDVQQKEwtIeXBlcmxlZGdlcjEPMA0GA1UECxMGRmFi
        cmljMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE3ioaunQmeYO30yyPW5RkitNr
        LKU39yH/r5Q4hSO7cUwn5IcF559OzATpAJjsKGGvarGfskEsjn/xTlTbYT8r2KOB
        ujCBtzAOBgNVHQ8BAf8EBAMCAaYwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUF
        BwMBMA8GA1UdEwEB/wQFMAMBAf8wKQYDVR0OBCIEIOU+zCvK/LXXJ+UkOm3U+d/3
        yXW+4kpWSwAFXHhtS0GEMEoGA1UdEQRDMEGCCWxvY2FsaG9zdIIHb3JnMi1jYYIM
        b3JnMi1jYS5vcmcyghdvcmcyLWNhLmhsZi5jaGlraXRzYS5pb4cEfwAAATAKBggq
        hkjOPQQDAgNJADBGAiEA5gPHuJrTAcUIBY6MbR2PeRLJswru4y+qd6zaqsfCYa4C
        IQCmPdJdrIChBh0YX61xYMFTKAR5F8WDFeCnKCyJF62Saw==
        -----END CERTIFICATE-----
    url: https://org2-ca.hlf.chikitsa.io:443
channels:
  _default:
    orderers:
    - orderer-node1.orderer
    peers:
      org1-peer1.org1:
        chaincodeQuery: true
        discover: true
        endorsingPeer: true
        eventSource: true
        ledgerQuery: true
      org1-peer2.org1:
        chaincodeQuery: true
        discover: true
        endorsingPeer: true
        eventSource: true
        ledgerQuery: true
      org2-peer1.org2:
        chaincodeQuery: true
        discover: true
        endorsingPeer: true
        eventSource: true
        ledgerQuery: true
      org2-peer2.org2:
        chaincodeQuery: true
        discover: true
        endorsingPeer: true
        eventSource: true
        ledgerQuery: true
client:
  organization: <no value>
name: hlf-network
orderers:
  orderer-node1.orderer:
    grpcOptions:
      allow-insecure: false
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICRDCCAeugAwIBAgIQCKU9lVLVPGSoyr6mNeqb/zAKBggqhkjOPQQDAjBtMQsw
        CQYDVQQGEwJFUzERMA8GA1UEBxMIQWxpY2FudGUxETAPBgNVBAkTCEFsaWNhbnRl
        MRkwFwYDVQQKExBLdW5nIEZ1IFNvZnR3YXJlMQ0wCwYDVQQLEwRUZWNoMQ4wDAYD
        VQQDEwV0bHNjYTAeFw0yMzExMjExNjEwNDhaFw0zMzExMjIxNjEwNDhaMG0xCzAJ
        BgNVBAYTAkVTMREwDwYDVQQHEwhBbGljYW50ZTERMA8GA1UECRMIQWxpY2FudGUx
        GTAXBgNVBAoTEEt1bmcgRnUgU29mdHdhcmUxDTALBgNVBAsTBFRlY2gxDjAMBgNV
        BAMTBXRsc2NhMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE7xCyQPLnOxakbH/u
        37KmAfss1+VidKxYeUiSzzJ7YR5UbSoVkByNlF9WavCUjqBcwcml9tvn64lbWlGL
        aYu7waNtMGswDgYDVR0PAQH/BAQDAgGmMB0GA1UdJQQWMBQGCCsGAQUFBwMCBggr
        BgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1UdDgQiBCBCndUXIhrL7vt0TDVn
        I56ZY5qDV3vdCuvDZ3aqr+ugBTAKBggqhkjOPQQDAgNHADBEAiAdzz9a1Ds+Dg03
        COb5Y69IMBpwIrytcgkqHSYiLt0XpgIgJ/LpPMOlEwNGeJqlxE0MXOF6GEhph9aO
        FakyEiZEadY=
        -----END CERTIFICATE-----
    url: grpcs://orderer1-ord.hlf.chikitsa.io:443
organizations:
  OrdererMSP:
    cryptoPath: /tmp/cryptopath
    mspid: OrdererMSP
    orderers:
    - orderer-node1.orderer
    peers: []
    users: {}
  Org1MSP:
    cryptoPath: /tmp/cryptopath
    mspid: Org1MSP
    orderers: []
    peers:
    - org1-peer1.org1
    - org1-peer2.org1
    users:
      admin:
        cert:
          pem: |
            -----BEGIN CERTIFICATE-----
            MIICUzCCAfmgAwIBAgIUQE/VmQo7yBSDRMO50+KpUzCGaxcwCgYIKoZIzj0EAwIw
            ajELMAkGA1UEBhMCRVMxETAPBgNVBAcTCEFsaWNhbnRlMREwDwYDVQQJEwhBbGlj
            YW50ZTEZMBcGA1UEChMQS3VuZyBGdSBTb2Z0d2FyZTENMAsGA1UECxMEVGVjaDEL
            MAkGA1UEAxMCY2EwHhcNMjMxMTIxMTYxMDA4WhcNMjQxMTIxMTYxNjAwWjAgMQ4w
            DAYDVQQLEwVhZG1pbjEOMAwGA1UEAxMFYWRtaW4wWTATBgcqhkjOPQIBBggqhkjO
            PQMBBwNCAAREu8eUrBXM8NtntYe9G3cTGHkiwuNaT9mhl+z5ndfot04Lipj4z1JQ
            K2cCMzjbUexcvDap6cxtFynFWzmM+lJQo4HGMIHDMA4GA1UdDwEB/wQEAwIHgDAM
            BgNVHRMBAf8EAjAAMB0GA1UdDgQWBBS2AW0RlbAA81qg9x04PCo4IVrYIjArBgNV
            HSMEJDAigCAUmi9bQGwKduk8+/ITWpPeIKa2bKME3iPHS4wKFm1eMTBXBggqAwQF
            BgcIAQRLeyJhdHRycyI6eyJoZi5BZmZpbGlhdGlvbiI6IiIsImhmLkVucm9sbG1l
            bnRJRCI6ImFkbWluIiwiaGYuVHlwZSI6ImFkbWluIn19MAoGCCqGSM49BAMCA0gA
            MEUCIQDtZb8EgZA/0Vz43xwBgE2khsI8O5BVTAV/b7VLeak2EAIgVMb3H3fcUUCS
            KLSfXsdwwO1S7Yw60rErWR3rFdCXnVA=
            -----END CERTIFICATE-----
        key:
          pem: |
            -----BEGIN PRIVATE KEY-----
            MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgRfLu+D3Dg1rSXCBq
            bSFjQKhTZsFIN2DT9IXjVptZG5ChRANCAAREu8eUrBXM8NtntYe9G3cTGHkiwuNa
            T9mhl+z5ndfot04Lipj4z1JQK2cCMzjbUexcvDap6cxtFynFWzmM+lJQ
            -----END PRIVATE KEY-----
  Org2MSP:
    cryptoPath: /tmp/cryptopath
    mspid: Org2MSP
    orderers: []
    peers:
    - org2-peer1.org2
    - org2-peer2.org2
    users:
      admin:
        cert:
          pem: |
            -----BEGIN CERTIFICATE-----
            MIICUjCCAfmgAwIBAgIUX/XxjrXzth6CNZA0w0ttVb0fex0wCgYIKoZIzj0EAwIw
            ajELMAkGA1UEBhMCRVMxETAPBgNVBAcTCEFsaWNhbnRlMREwDwYDVQQJEwhBbGlj
            YW50ZTEZMBcGA1UEChMQS3VuZyBGdSBTb2Z0d2FyZTENMAsGA1UECxMEVGVjaDEL
            MAkGA1UEAxMCY2EwHhcNMjMxMTIxMTYxMDI4WhcNMjQxMTIxMTYxNzAwWjAgMQ4w
            DAYDVQQLEwVhZG1pbjEOMAwGA1UEAxMFYWRtaW4wWTATBgcqhkjOPQIBBggqhkjO
            PQMBBwNCAASCH1MH4ocF25K33kGgVzmyWocXT1zflH5r6ms5yDSka8aokf6Lv0R/
            U9w/gsG0IN/CezQFCfL+7qEhDrqQC9DJo4HGMIHDMA4GA1UdDwEB/wQEAwIHgDAM
            BgNVHRMBAf8EAjAAMB0GA1UdDgQWBBTgfE5ZcovL+Wyac2M245dGnVWN9zArBgNV
            HSMEJDAigCAaOLiSyKHzNwS27B7u4r1SbgrIZPflDz7Y7AvO/CJT3jBXBggqAwQF
            BgcIAQRLeyJhdHRycyI6eyJoZi5BZmZpbGlhdGlvbiI6IiIsImhmLkVucm9sbG1l
            bnRJRCI6ImFkbWluIiwiaGYuVHlwZSI6ImFkbWluIn19MAoGCCqGSM49BAMCA0cA
            MEQCIDGOc9DyxI5HT+ovme/ETN8VHpb1Oxm54mhibdWtYEweAiAqmoGHflma+80M
            tisaqvSbgIZvPo/L2QVBrtGEYRJP8g==
            -----END CERTIFICATE-----
        key:
          pem: |
            -----BEGIN PRIVATE KEY-----
            MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgRzUICE6kVC1g2zxH
            V0y068qhsDAVMaLxQvFv8GiC0r6hRANCAASCH1MH4ocF25K33kGgVzmyWocXT1zf
            lH5r6ms5yDSka8aokf6Lv0R/U9w/gsG0IN/CezQFCfL+7qEhDrqQC9DJ
            -----END PRIVATE KEY-----
peers:
  org1-peer1.org1:
    grpcOptions:
      allow-insecure: false
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICRjCCAeugAwIBAgIQIT5QWq3fgF9he2reRUxuITAKBggqhkjOPQQDAjBtMQsw
        CQYDVQQGEwJFUzERMA8GA1UEBxMIQWxpY2FudGUxETAPBgNVBAkTCEFsaWNhbnRl
        MRkwFwYDVQQKExBLdW5nIEZ1IFNvZnR3YXJlMQ0wCwYDVQQLEwRUZWNoMQ4wDAYD
        VQQDEwV0bHNjYTAeFw0yMzExMjExNjEwMDhaFw0zMzExMjIxNjEwMDhaMG0xCzAJ
        BgNVBAYTAkVTMREwDwYDVQQHEwhBbGljYW50ZTERMA8GA1UECRMIQWxpY2FudGUx
        GTAXBgNVBAoTEEt1bmcgRnUgU29mdHdhcmUxDTALBgNVBAsTBFRlY2gxDjAMBgNV
        BAMTBXRsc2NhMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEQEL3WRvCKv/zegOb
        rNtIQlngjAxUytd3vk7tJ48X05BN1eEUr+hoLXQw0hrdhd2vwZPjgkDG26ezCb1E
        iER2N6NtMGswDgYDVR0PAQH/BAQDAgGmMB0GA1UdJQQWMBQGCCsGAQUFBwMCBggr
        BgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1UdDgQiBCAZr5Wh4xajGArWrVVj
        p2iCk0zsdwrPQkLITL9Dy4qopjAKBggqhkjOPQQDAgNJADBGAiEA4soM6ML0TC3p
        6PrqoYCH0uvTY/cK0FMZmVRkrG1J3WwCIQD8l4L3KHyfAWPipltJcMYBMPPGL9aM
        8wsV2AySyKr/4w==
        -----END CERTIFICATE-----
    url: grpcs://peer1-org1.hlf.chikitsa.io:443
  org1-peer2.org1:
    grpcOptions:
      allow-insecure: false
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICRjCCAeugAwIBAgIQIT5QWq3fgF9he2reRUxuITAKBggqhkjOPQQDAjBtMQsw
        CQYDVQQGEwJFUzERMA8GA1UEBxMIQWxpY2FudGUxETAPBgNVBAkTCEFsaWNhbnRl
        MRkwFwYDVQQKExBLdW5nIEZ1IFNvZnR3YXJlMQ0wCwYDVQQLEwRUZWNoMQ4wDAYD
        VQQDEwV0bHNjYTAeFw0yMzExMjExNjEwMDhaFw0zMzExMjIxNjEwMDhaMG0xCzAJ
        BgNVBAYTAkVTMREwDwYDVQQHEwhBbGljYW50ZTERMA8GA1UECRMIQWxpY2FudGUx
        GTAXBgNVBAoTEEt1bmcgRnUgU29mdHdhcmUxDTALBgNVBAsTBFRlY2gxDjAMBgNV
        BAMTBXRsc2NhMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEQEL3WRvCKv/zegOb
        rNtIQlngjAxUytd3vk7tJ48X05BN1eEUr+hoLXQw0hrdhd2vwZPjgkDG26ezCb1E
        iER2N6NtMGswDgYDVR0PAQH/BAQDAgGmMB0GA1UdJQQWMBQGCCsGAQUFBwMCBggr
        BgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1UdDgQiBCAZr5Wh4xajGArWrVVj
        p2iCk0zsdwrPQkLITL9Dy4qopjAKBggqhkjOPQQDAgNJADBGAiEA4soM6ML0TC3p
        6PrqoYCH0uvTY/cK0FMZmVRkrG1J3WwCIQD8l4L3KHyfAWPipltJcMYBMPPGL9aM
        8wsV2AySyKr/4w==
        -----END CERTIFICATE-----
    url: grpcs://peer2-org1.hlf.chikitsa.io:443
  org2-peer1.org2:
    grpcOptions:
      allow-insecure: false
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICRzCCAeygAwIBAgIRAI2BiSZ2FFAZDAJYrhIOecgwCgYIKoZIzj0EAwIwbTEL
        MAkGA1UEBhMCRVMxETAPBgNVBAcTCEFsaWNhbnRlMREwDwYDVQQJEwhBbGljYW50
        ZTEZMBcGA1UEChMQS3VuZyBGdSBTb2Z0d2FyZTENMAsGA1UECxMEVGVjaDEOMAwG
        A1UEAxMFdGxzY2EwHhcNMjMxMTIxMTYxMDI4WhcNMzMxMTIyMTYxMDI4WjBtMQsw
        CQYDVQQGEwJFUzERMA8GA1UEBxMIQWxpY2FudGUxETAPBgNVBAkTCEFsaWNhbnRl
        MRkwFwYDVQQKExBLdW5nIEZ1IFNvZnR3YXJlMQ0wCwYDVQQLEwRUZWNoMQ4wDAYD
        VQQDEwV0bHNjYTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABOM/5DOET27pTN0x
        7FQnFB3LoyMrugvImFzt9/7JLuyFMjgeOQtoDBIavN7Bc+eggPt6t8ULJ7+4/QxM
        8cmM1wSjbTBrMA4GA1UdDwEB/wQEAwIBpjAdBgNVHSUEFjAUBggrBgEFBQcDAgYI
        KwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zApBgNVHQ4EIgQgNEnXLjjIGJcQe9gi
        tORWlyHiWLp17ajHu+AyNrAOcHcwCgYIKoZIzj0EAwIDSQAwRgIhAIE3IoyJeez2
        WYwltb/dfoPBqq5P4xyvHQUrtQ0UfKtqAiEAqM/Htms7jsOBDejEsfI35AMaxWh3
        CJQA/ApHS83+76E=
        -----END CERTIFICATE-----
    url: grpcs://peer1-org2.hlf.chikitsa.io:443
  org2-peer2.org2:
    grpcOptions:
      allow-insecure: false
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICRzCCAeygAwIBAgIRAI2BiSZ2FFAZDAJYrhIOecgwCgYIKoZIzj0EAwIwbTEL
        MAkGA1UEBhMCRVMxETAPBgNVBAcTCEFsaWNhbnRlMREwDwYDVQQJEwhBbGljYW50
        ZTEZMBcGA1UEChMQS3VuZyBGdSBTb2Z0d2FyZTENMAsGA1UECxMEVGVjaDEOMAwG
        A1UEAxMFdGxzY2EwHhcNMjMxMTIxMTYxMDI4WhcNMzMxMTIyMTYxMDI4WjBtMQsw
        CQYDVQQGEwJFUzERMA8GA1UEBxMIQWxpY2FudGUxETAPBgNVBAkTCEFsaWNhbnRl
        MRkwFwYDVQQKExBLdW5nIEZ1IFNvZnR3YXJlMQ0wCwYDVQQLEwRUZWNoMQ4wDAYD
        VQQDEwV0bHNjYTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABOM/5DOET27pTN0x
        7FQnFB3LoyMrugvImFzt9/7JLuyFMjgeOQtoDBIavN7Bc+eggPt6t8ULJ7+4/QxM
        8cmM1wSjbTBrMA4GA1UdDwEB/wQEAwIBpjAdBgNVHSUEFjAUBggrBgEFBQcDAgYI
        KwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zApBgNVHQ4EIgQgNEnXLjjIGJcQe9gi
        tORWlyHiWLp17ajHu+AyNrAOcHcwCgYIKoZIzj0EAwIDSQAwRgIhAIE3IoyJeez2
        WYwltb/dfoPBqq5P4xyvHQUrtQ0UfKtqAiEAqM/Htms7jsOBDejEsfI35AMaxWh3
        CJQA/ApHS83+76E=
        -----END CERTIFICATE-----
    url: grpcs://peer2-org2.hlf.chikitsa.io:443
version: 1.0.0
