apiVersion : apps/v1
kind: Deployment
metadata:
  name: bhanuprakashhlfclientaks 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bhanuprakashhlfclientaks
  template:
    metadata:
      labels:
        app: bhanuprakashhlfclientaks 
    spec:
      containers:
        - name: bhanuprakashhlfclientaks 
          image: fabricregistry03.azurecr.io/bhanuprakashhlfclientaks
          ports:
          - containerPort: 3000